services:
  backend:
    container_name: library_backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  frontend:
    container_name: library_frontend
    # build: ./frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile_prod
    ports:
      # - "5173:5173"
      - "80:80"
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
  postgres:
    image: postgres:17
    container_name: library_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
