services:
  backend:
    container_name: library_backend
    build: ./backend
    ports:
      - "8000:8000"
    # volumes:
    # - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
  frontend:
    container_name: library_frontend
    # build: ./frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile_prod
    ports:
      # - "5173:5173"
      - "80:80"
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    depends_on:
      - backend
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d library_db"]
      interval: 5s
      timeout: 5s
      retries: 10
